### ISSUE TITLE
Map vitems update

### ISSUE THREAD

**Issue by fresqo** [StrayaGamingTanoa/StrayaGaming.Tanoa#17]
Larry please change all instances of :
oilUnprocessed TO oil_unprocessed
copperUnrefined TO copper_unrefined
ironUnrefined TO iron_unrefined
saltUnrefined TO salt_unrefined
diamondUncut TO diamond_uncut
heroinUnprocessed TO heroin_unprocessed
cocaineUnprocessed TO cocaine_unprocessed

**Comment by LarryLancelot** [comment]
All processors have been fixed. SQM will be updated this afternoon.
