### ISSUE TITLE
Infishit update with Vehicles and weapons

### ISSUE THREAD

**Issue by fresqo** [StrayaGamingTanoa/StrayaGaming.Tanoa#22]
- Once shops are finalized. Need to add all new Weapons, ammo and vehicles to infistar
- will be using all vehicles and all weapons in game so remove some restrictions when time comes.

**Comment by fresqo** [comment]
will be using all vehicles and all weapons in game so remove some restrictions when time comes.

**Comment by fresqo** [comment]
made an adjustment for vehicle checks... please test

**Comment by envycam** [comment]
all tested, closing
