### ISSUE TITLE
Whitelisting - Ranks

### ISSUE THREAD

**Issue by fresqo** [StrayaGamingTanoa/StrayaGaming.Tanoa#5]
- [ ] LCPL, Corporal, Sergeant, Warrant Officer 2, 2nd Liutenant, Liutenant, Captain, Major, Colonel, Brigadier, Commodore and General
- [x] Create all the ranks in the config files as well as query the database to allow that many ranks.
- [x] Create whitelisted shops for the cops that align with the ranks created in the config files. Refer to Loadout and Vehicle Access Tab on the Google Docs.
- [x] Remove the rebel license from the rebel outposts so that it has to be given manually through the database.

**Comment by fresqo** [comment]
for the rebel license removal, just remove the addaction to buy on map.. refer @LarryLancelot

**Comment by LarryLancelot** [comment]
REBEL liscence's removed from the shops
