### ISSUE TITLE
THINGS TO TEST LIST

### ISSUE THREAD

**Issue by fresqo** [StrayaGamingTanoa/StrayaGaming.Tanoa#55]
- [x] Military can send to prison
- [x] Military can restrain (and give description how restrain works)
- [x] Military get paid once killing a wanted civ
- [x] Military get paid when crim gets released from prison
- [x] Inmate can post bail
- [x] Inmate has illegal items removed etc
- [x] Players can rob Federal reserve
- [ ] Military get notified when fed is a) started via boltcutting b) blasting charge
- [x] Military can lock up fed, both dome, shed and crate
- [x] Does house raiding notify players or military
- [x] Does house crates work and save nicely
- [x] All prices
- [x] Check chop shop works (and detail which vehicles, ie cars helis etc)
- [x] Check all runs work (hints, strings & money gets taken/paid correctly)
- [x] Check all licenses are purchasable (hints and strings are correct)
- [x] Check vehicle spawn points work (single/multiple amounts spawned doesnt dissappear)

**Comment by spacebuff** [comment]
- [ ] Add in Chop Shops

- [ ] Take out Blackfish from Civ Air Shops
