### ISSUE TITLE
Things I have tested and found issues (Marc)

### ISSUE THREAD

**Issue by spacebuff** [StrayaGamingTanoa/StrayaGaming.Tanoa#63]
- [x] Add in Chop Shops
- [x] Take out Blackfish from Civ Air Shops
- [x]  Bad spawn for Air Garage, at main Guerrilla Island (Lhaven)
- [x]  Bad Spawn at Car Garage at Moddergat
- [x]  Bad Spawn at Car Garage at (Lhaven)
- [x]  Fishing areas marked on map

**Comment by envycam** [comment]
Blackfish has been removed @spacebuff

**Comment by fresqo** [comment]
fishing areas not working?
