### ISSUE TITLE
Infishit

### ISSUE THREAD

**Issue by fresqo** [StrayaGamingTanoa/StrayaGaming.Tanoa#7]
- please get me admins ID's plez
- And ranks and tools wanted.

**Comment by envycam** [comment]
Marc - 76561198039194966
Envy - 76561198057431599
Col - 76561198046060990
Full access, we will discuss the rest of them later.

**Comment by fresqo** [comment]
Any admin with any normal menu access will need to be in infistar due to the restrictions. At least it was like this in the version I used. I can put the rest in infistar but with zero access
